### ISSUE TITLE
Ferramenta para extrair os dados dos mentorados diretamente da planilha no Google Sheets.

### ISSUE THREAD

**Issue by carvalhodanielg** [pedromarins/comunidade-code-mapa#1]
## Ferramenta:
 Extract GSheet: [Documentação](https://github.com/ngblaylock/extract-gsheet)

## Observações:
A documentação da ferramenta explica bem a sua utilização. Já fiz alguns testes e funcionou perfeitamente. 
Algumas questões importantes que notei fazendo os testes foram:
1- Se tiver alguma linha vazia na planilha, na coluna das coordenadas, pode dar problema na aplicação.
2- Quando a planilha é atualizada, demora cerca de 5 minutos para os dados serem atualizados.

**Comment by pedromarins** [comment]
Aplicamos a biblioteca sugerida pelo [carvalhodanielg](https://github.com/carvalhodanielg) no commit [Carregar dinamicamente os dados dos mentorados da planilha oficial
](https://github.com/pedromarins/comunidade-code-mapa/commit/f4290760fbbce1491ac04b8f3b5c32dd608408ab)!

Obrigado pelo apoio Daniel!
