### ISSUE TITLE
Remover botão do zoom

### ISSUE THREAD

**Issue by gabegodoy** [pedromarins/comunidade-code-mapa#4]
### Quando botão do zoom é utilizado, o header some da tela

-> Retirar os botões via **CSS**

**Comment by gabegodoy** [comment]
A funcionalidade do scroll nos (devices mouse) e no efeito pinça nos (devices mobile) está em dia!

**Comment by henriquecrang** [comment]
Entendi! Então, como esse botão está quebrado, entendo que faça sentido o esconder imediatamente.

Mas, pensando na usabilidade da ferramenta, acredito que seria importante ter o botão ali funcional.

Podemos fechar essa issue escondendo o botão e criar outra para adicionar botões de zoom funcionais!

**Comment by gabegodoy** [comment]
Excelente sugestão!
